name: discord notify

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.8.5
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "Hi!"
          username: GitHub Actions
